# Auto-generated by Wutong ASI agent
# Import necessary libraries
import requests

# Define the URL for the ASI API endpoint
url = "https://api.wutong.com/v1/models"

# Set headers for the request
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer YOUR_API_KEY"
}

# Define the payload for the API call
payload = {
    "models": [
        {
            "name": "Model1",
            "description": "Description of Model 1",
            "parameters": {
                "learning_rate": 0.01,
                "batch_size": 32
            }
        },
        {
            "name": "Model2",
            "description": "Description of Model 2",
            "parameters": {
                "num_epochs": 10,
                "hidden_units": 64
            }
        },
        {
            "name": "Model3",
            "description": "Description of Model 3",
            "parameters": {
                "learning_rate": 0.05,
                "dropout_rate": 0.2
            }
        }
    ]
}

# Send a POST request to the ASI API endpoint
response = requests.post(url, headers=headers, json=payload)

# Print the response from the API
print(response.json())