# Auto-generated by Wutong ASI agent
# Import necessary libraries
import requests
import json

# Define the base URL of the Wutong ASI API
base_url = "http://api.wutongasi.com"

# Define the headers for API requests
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer your_access_token"
}

# Define the payload to send a request
payload = {
    "model": "local_model1",
    "input_text": "Hello, how are you?"
}

# Send a POST request to the Wutong ASI API
response = requests.post(f"{base_url}/process", headers=headers, json=payload)

# Parse the JSON response
response_data = json.loads(response.text)

# Print the response data
print(response_data)