# Auto-generated by Wutong ASI agent
import requests
import json

# Define the URL of the Wutong ASI API
url = "https://example.com/api/v1/self-evolving-ai"

# Define the headers for the request
headers = {
    "Content-Type": "application/json"
}

# Define the data payload for the request
data = {
    "model_type": "local",
    "local_models": ["model1", "model2", "model3", "model4", "model5"]
}

# Send a POST request to the Wutong ASI API
response = requests.post(url, headers=headers, data=json.dumps(data))

# Print the response status code and content
print(f"Status Code: {response.status_code}")
print(f"Response Content: {response.json()}")