# Auto-generated by Wutong ASI
# Import necessary libraries
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load the pre-trained model and tokenizer from Hugging Face's model hub
model_name = "Qwen/Qwen-7B"  # Replace this with your specific model name
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

def query(question):
    """
    Function to interact with the self-evolving AI API service.
    
    Args:
        question (str): The input question or prompt for the AI to respond to.
        
    Returns:
        str: The response generated by the AI model.
    """
    # Tokenize the input question
    inputs = tokenizer(question, return_tensors="pt")
    
    # Generate a response using the model
    with torch.no_grad():
        outputs = model.generate(**inputs, max_length=50)  # Adjust max_length as needed
    
    # Decode and return the generated response
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

# Example usage of the query function
user_question = "What is the capital of Peru?"
ai_response = query(user_question)
print(f"AI Response: {ai_response}")