# Auto-generated by Wutong ASI
# Import necessary libraries for AI services
import requests

# Define the URL for the self-evolving AI API
api_url = "https://api.selfevolvingai.com/v1/predict"

# Set up the headers, including your API key for authentication
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer YOUR_API_KEY"
}

# Define a function to interact with the self-evolving AI model
def query_ai(question):
    """
    This function takes a question as input and queries the self-evolving AI model
    for an answer. It then prints out the response.
    
    Args:
    - question (str): The user's question to be passed to the AI model
    
    Returns:
    None
    """
    # Data payload containing the question
    data = {
        "question": question
    }
    
    # Make a POST request to the API with headers and JSON data
    response = requests.post(api_url, headers=headers, json=data)
    
    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        answer = response.json()['answer']
        print(f"AI: {answer}")
    else:
        print("Error in fetching data from the API.")

# Example usage of the query_ai function
if __name__ == "__main__":
    user_question = "What is the capital of Peru?"
    query_ai(user_question)