# Auto-generated by Wutong ASI
# Import necessary libraries
import requests

import requests

def generate_ai_prompt(prompt):
    """
    Generate the AI prompt.

    Args:
    prompt (str): The input string for the AI model.

    Returns:
    str: The AI prompt.
    """
    return {"prompt": prompt}

def create_headers():
    """
    Create headers for the API request.

    Returns:
    dict: Headers to be included in the request.
    """
    return {
        "Content-Type": "application/json",
        "Authorization": "Bearer YOUR_API_KEY"  # Replace with your actual API key
    }

def call_ai_service(prompt):
    """
    Function to call the self-evolving AI API service.

    Args:
    prompt (str): The input string for the AI model.

    Returns:
    str: The output from the AI model.
    """
    url = "https://api.selfevolvingai.com/generate"
    headers = create_headers()
    data = generate_ai_prompt(prompt)

    response = requests.post(url, headers=headers, json=data)
    response.raise_for_status()  # Raises an HTTPError for bad responses
    return response.json().get("output")

# Example usage of the function
if __name__ == "__main__":
    user_prompt = "Translate 'Hello, world!' into Spanish."
    ai_response = call_ai_service(user_prompt)
    print(f"AI Response: {ai_response}")