# Auto-generated by Wutong ASI
# Import necessary libraries
import requests

# Define the initial prompt for the AI model
prompt = "Write a Python function that calculates the factorial of a number."

# Function to interact with the AI API and get response
import requests

def get_api_endpoint():
    """Return the AI API endpoint."""
    return "https://your-api-endpoint"

def get_headers():
    """Set up headers for the API request, including authorization if required."""
    return {
        "Content-Type": "application/json",
        "Authorization": "Bearer your-access-token"
    }

def construct_payload(prompt):
    """Construct the payload to send with the AI API request."""
    return {"prompt": prompt}

def query_ai_api(prompt):
    """
    Query data from AI API and return response.

    Parameters:
    - prompt (str): The input prompt for the AI model.

    Returns:
    - dict: The response from the AI API.
    """
    api_endpoint = get_api_endpoint()
    headers = get_headers()
    payload = construct_payload(prompt)

    response = requests.post(api_endpoint, headers=headers, json=payload)
    response.raise_for_status()  # Raise an exception for HTTP errors
    return response.json()

# Call the function and store the AI's response
ai_response = query_ai_api(prompt)

# Print out the AI's response
print("AI Response:")
print(ai_response)