# Auto-generated by Wutong ASI
# Import necessary libraries
import requests

# Define the initial prompt for the AI model
prompt = "Write a Python function that calculates the factorial of a number."

# Function to interact with the AI API and get response
def query_ai_api(prompt):
    """```python
# Query data from AI API and return response
```

This docstring provides a brief description of what the `query_ai_api` function does, including its purpose, parameters, and expected output. It should be concise yet informative,"""
    # Replace 'your-api-endpoint' with actual AI API endpoint
    api_endpoint = "https://your-api-endpoint"
    
    # Set up headers, usually including an authorization token if required
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer your-access-token"
    }
    
    # Payload containing the prompt to be sent to the AI model
    payload = {
        "prompt": prompt,
        "temperature": 0.7,  # Controls randomness of responses
        "max_tokens": 150   # Maximum number of tokens in the response
    }
    
    # Send a POST request to the API endpoint with headers and payload
    response = requests.post(api_endpoint, json=payload, headers=headers)
    
    # Check if the response status code is OK (200)
    if response.status_code == 200:
        # Return the generated text from the API response
        return response.json().get('choices')[0].get('text').strip()
    else:
        # Raise an exception with error message if something went wrong
        raise Exception(f"Error: {response.status_code} - {response.text}")

# Call the function and store the AI's response
ai_response = query_ai_api(prompt)

# Print out the AI's response
print("AI Response:")
print(ai_response)